# Generated by Django 6.0.3 on 2026-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_beans_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
